### ISSUE TITLE
Docker agent failed to run any job

### ISSUE THREAD

**Issue by nitrogear** [jenkinsci/docker-agent#65]
Hello.

I use docker image jenkins/slave with buildpack-deps:scm. When I start any job with docker slave agent I get the following error:
```
[06/25/19 11:12:01] Launching agent
$ docker start --interactive --attach 2221dc966d9a7500675b6fc74f2a2f67848777fa60f78cfed30e5e46c56b45f3
<===[JENKINS REMOTING CAPACITY]===>channel started
Remoting version: 3.33
This is a Unix agent
Jun 25, 2019 11:12:06 AM org.jenkinsci.remoting.util.AnonymousClassWarnings warn
WARNING: Attempt to (de-)serialize anonymous class org.jenkinsci.plugins.envinject.EnvInjectComputerListener$2; see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
Agent successfully connected and online
[EnvInject] - Loading node environment variables.
Building remotely on Container for Docker_Slave_Test#17 in workspace /home/jenkins/workspace/Docker_Slave_Test
FATAL: Unable to produce a script file
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at hudson.FilePath$CreateTextTempFile.invoke(FilePath.java:1469)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to Container for Docker_Slave_Test#17
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:957)
		at hudson.FilePath.act(FilePath.java:1072)
		at hudson.FilePath.act(FilePath.java:1061)
		at hudson.FilePath.createTextTempFile(FilePath.java:1443)
		at hudson.tasks.CommandInterpreter.createScriptFile(CommandInterpreter.java:162)
		at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:94)
		at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
		at hudson.model.Build$BuildExecution.build(Build.java:206)
		at hudson.model.Build$BuildExecution.doRun(Build.java:163)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
		at hudson.model.Run.execute(Run.java:1818)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
Caused: java.io.IOException: Failed to create a temporary directory in /home/jenkins/.tmp
	at hudson.FilePath$CreateTextTempFile.invoke(FilePath.java:1471)
	at hudson.FilePath$CreateTextTempFile.invoke(FilePath.java:1448)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3052)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: java.io.IOException: Failed to create a temp file on /home/jenkins/workspace/Docker_Slave_Test
	at hudson.FilePath.createTextTempFile(FilePath.java:1445)
	at hudson.tasks.CommandInterpreter.createScriptFile(CommandInterpreter.java:162)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:94)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1818)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Execute shell' marked build as failure
Error getting resources from path
Reported exception:
java.nio.file.NoSuchFileException: /home/jenkins/.tmp/resource-4547264205628567592
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
	at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173)
	at java.nio.file.Files.createTempDirectory(Files.java:991)
	at hudson.remoting.Util.makeResource(Util.java:60)
	at hudson.remoting.ResourceImageDirect.resolveURL(ResourceImageDirect.java:40)
	at hudson.remoting.ResourceImageBoth.resolveURL(ResourceImageBoth.java:33)
	at hudson.remoting.RemoteClassLoader.findResources(RemoteClassLoader.java:490)
	at java.lang.ClassLoader.getResources(ClassLoader.java:1142)
	at org.slf4j.LoggerFactory.findPossibleStaticLoggerBinderPathSet(LoggerFactory.java:303)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:146)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
	at org.apache.commons.beanutils.ConvertUtilsBean.<init>(ConvertUtilsBean.java:154)
	at org.kohsuke.stapler.Stapler.<clinit>(Stapler.java:1073)
	at hudson.model.Node$Mode.<clinit>(Node.java:596)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.lang.Class.getEnumConstantsShared(Class.java:3320)
	at java.lang.Class.getEnumConstants(Class.java:3297)
	at jenkins.model.Jenkins.<clinit>(Jenkins.java:5243)
	at hudson.model.Computer.<clinit>(Computer.java:1768)
	at hudson.util.ProcessTree.get(ProcessTree.java:414)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1103)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1094)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE
```

Any ideas how how it could be solved?

**Comment by slide** [comment]
Can you give some information on how you are running the docker agent? What is the command line being used?

**Comment by li-adrienloiseau** [comment]
@nitrogear your problem has been solved ?

**Comment by andreisohan** [comment]
any update on this topic? I encounter the same problem.

**Comment by slide** [comment]
Since we didn't receive answers to our previous questions, there has been no progress made.

**Comment by GioMac** [comment]
still there...

**Comment by MarkEWaite** [comment]
> still there...

Unfortunately, I doubt that statement will bring anyone closer to understanding how to duplicate the problem.  Without being able to duplicate the problem, it is extremely difficult to fix the problem.

Can you provide detailed steps that will allow others to duplicate the problem in a fresh install?

**Comment by GioMac** [comment]
Centos 7 (updates as of 06-05-2020)
OpenJDK 11:
`java-11-openjdk-11.0.7.10-4.el7_8.x86_64`
Docker packages:
`docker-client-1.13.1-161.git64e9980.el7_8.x86_64
docker-compose-1.18.0-4.el7.noarch
docker-1.13.1-161.git64e9980.el7_8.x86_64
python36-dockerpty-0.4.1-18.el7.noarch
python36-docker-2.6.1-3.el7.noarch
docker-common-1.13.1-161.git64e9980.el7_8.x86_64`
Docker image specified for build: centos:8
Remoting image: jenkins/slave:3.27-1
SCM Docker image:buildpack-deps:scm
Connected via UNIX socket


Log:
```
Started by user George Machitidze
Running as SYSTEM
Start Docker container to host the build
[05/06/20 23:19:44] Launching agent
$ docker -H unix:///var/run/docker.sock start --interactive --attach 96ad2371ae5df05fd97c36d0af89050822dd45943fef7a28950cd15d29c63934
<===[JENKINS REMOTING CAPACITY]===>channel started
Remoting version: 4.2
This is a Unix agent
Agent successfully connected and online
Building remotely on Container for test#15 in workspace /home/jenkins/workspace/test
FATAL: Unable to produce a script file
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at hudson.FilePath$CreateTextTempFile.invoke(FilePath.java:1466)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to Container for test#15
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1788)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:998)
		at hudson.FilePath.act(FilePath.java:1069)
		at hudson.FilePath.act(FilePath.java:1058)
		at hudson.FilePath.createTextTempFile(FilePath.java:1440)
		at hudson.tasks.CommandInterpreter.createScriptFile(CommandInterpreter.java:162)
		at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:94)
		at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
		at hudson.model.Build$BuildExecution.build(Build.java:206)
		at hudson.model.Build$BuildExecution.doRun(Build.java:163)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
		at hudson.model.Run.execute(Run.java:1856)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:428)
Caused: java.io.IOException: Failed to create a temporary directory in /home/jenkins/.tmp
	at hudson.FilePath$CreateTextTempFile.invoke(FilePath.java:1468)
	at hudson.FilePath$CreateTextTempFile.invoke(FilePath.java:1445)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3069)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: java.io.IOException: Failed to create a temp file on /home/jenkins/workspace/test
	at hudson.FilePath.createTextTempFile(FilePath.java:1442)
	at hudson.tasks.CommandInterpreter.createScriptFile(CommandInterpreter.java:162)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:94)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1856)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Build step 'Execute shell' marked build as failure
Error getting resources from path
Reported exception:
java.nio.file.NoSuchFileException: /home/jenkins/.tmp/resource-1910961560186233123
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
	at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173)
	at java.nio.file.Files.createTempDirectory(Files.java:991)
	at hudson.remoting.Util.makeResource(Util.java:67)
	at hudson.remoting.ResourceImageDirect.resolveURL(ResourceImageDirect.java:43)
	at hudson.remoting.ResourceImageBoth.resolveURL(ResourceImageBoth.java:33)
	at hudson.remoting.RemoteClassLoader.findResources(RemoteClassLoader.java:492)
	at java.lang.ClassLoader.getResources(ClassLoader.java:1142)
	at org.slf4j.LoggerFactory.findPossibleStaticLoggerBinderPathSet(LoggerFactory.java:303)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:146)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
	at org.apache.commons.beanutils.ConvertUtilsBean.<init>(ConvertUtilsBean.java:154)
	at org.kohsuke.stapler.Stapler.<clinit>(Stapler.java:1073)
	at hudson.model.Node$Mode.<clinit>(Node.java:604)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.lang.Class.getEnumConstantsShared(Class.java:3320)
	at java.lang.Class.getEnumConstants(Class.java:3297)
	at jenkins.model.Jenkins.<clinit>(Jenkins.java:5338)
	at hudson.model.Computer.<clinit>(Computer.java:1803)
	at hudson.util.ProcessTree.get(ProcessTree.java:432)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1100)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1091)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```


awt.toolkit | sun.awt.X11.XToolkit
-- | --
com.zaxxer.hikari.pool_number | 1
executable-war | /usr/lib/jenkins/jenkins.war
file.encoding | UTF-8
file.separator | /
java.awt.graphicsenv | sun.awt.X11GraphicsEnvironment
java.awt.headless | true
java.awt.printerjob | sun.print.PSPrinterJob
java.class.path | /usr/lib/jenkins/jenkins.war
java.class.version | 55.0
java.home | /usr/lib/jvm/java-11-openjdk-11.0.7.10-4.el7_8.x86_64
java.io.tmpdir | /tmp
java.library.path | /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
java.runtime.name | OpenJDK Runtime Environment
java.runtime.version | 11.0.7+10-LTS
java.specification.name | Java Platform API Specification
java.specification.vendor | Oracle Corporation
java.specification.version | 11
java.vendor | Oracle Corporation
java.vendor.url | http://java.oracle.com/
java.vendor.url.bug | http://bugreport.java.com/bugreport/
java.vendor.version | 18.9
java.version | 11.0.7
java.version.date | 2020-04-14
java.vm.compressedOopsMode | 32-bit
java.vm.info | mixed mode, sharing
java.vm.name | OpenJDK 64-Bit Server VM
java.vm.specification.name | Java Virtual Machine Specification
java.vm.specification.vendor | Oracle Corporation
java.vm.specification.version | 11
java.vm.vendor | Oracle Corporation
java.vm.version | 11.0.7+10-LTS
jdk.debug | release
JENKINS_HOME | /var/lib/jenkins
jetty.git.hash | a304fd9f351f337e7c0e2a7c28878dd536149c6c
jna.loaded | true
jna.platform.library.path | /usr/lib64:/lib64:/usr/lib:/lib:/usr/lib64/varnish:/usr/lib64/mysql:/usr/lib64//bind9-export
jnidispatch.path | /var/lib/jenkins/.cache/JNA/temp/jna9643666236071066222.tmp
line.separator |  
mail.smtp.sendpartial | true
mail.smtps.sendpartial | true
os.arch | amd64
os.name | Linux
os.version | 3.10.0-1127.el7.x86_64
path.separator | :
sun.arch.data.model | 64
sun.boot.library.path | /usr/lib/jvm/java-11-openjdk-11.0.7.10-4.el7_8.x86_64/lib
sun.cpu.endian | little
sun.cpu.isalist |  
sun.font.fontmanager | sun.awt.X11FontManager
sun.io.unicode.encoding | UnicodeLittle
sun.java.command | /usr/lib/jenkins/jenkins.war --logfile=/var/log/jenkins/jenkins.log --webroot=/var/cache/jenkins/war --httpPort=8080 --debug=5 --handlerCountMax=100 --handlerCountMaxIdle=20
sun.java.launcher | SUN_STANDARD
sun.jnu.encoding | UTF-8
sun.management.compiler | HotSpot 64-Bit Tiered Compilers
sun.os.patch.level | unknown
svnkit.http.methods | Digest,Basic,NTLM,Negotiate
svnkit.ssh2.persistent | false
user.country | US
user.dir | /
user.home | /var/lib/jenkins
user.language | en
user.name | jenkins
user.timezone | Asia/Tbilisi


Name  ↓ | Value
-- | --
_ | /usr/lib/jvm/jre-11-openjdk/bin/java
HOME | /var/lib/jenkins
LANG | en_US.UTF-8
LOGNAME | jenkins
PATH | /sbin:/usr/sbin:/bin:/usr/bin
PWD | /
SHELL | /bin/bash
SHLVL | 2
USER | jenkins


Name  ↓ | Version | Enabled
-- | -- | --
ace-editor | 1.1 | true
active-directory | 2.16 | true
amazon-ecs | 1.34 | true
android-signing | 2.2.5 | true
ansicolor | 0.6.3 | true
ant | 1.11 | true
antisamy-markup-formatter | 2.0 | true
apache-httpcomponents-client-4-api | 4.5.10-2.0 | true
assertthat-bdd-jira | 1.3 | true
atlassian-jira-software-cloud | 1.1.0 | true
authentication-tokens | 1.3 | true
aws-bucket-credentials | 1.0.0 | true
aws-codebuild | 0.47 | true
aws-codecommit-jobs | 0.3.0 | true
aws-codecommit-trigger | 3.0.0 | true
aws-codepipeline | 0.41 | true
aws-credentials | 1.28 | true
aws-global-configuration | 1.3 | true
aws-java-sdk | 1.11.723 | true
aws-lambda | 0.5.10 | true
awseb-deployment-plugin | 0.3.20 | true
azure-ad | 1.2.0 | true
azure-commons | 1.0.4 | true
azure-credentials | 4.0.2 | true
azure-vm-agents | 1.4.1 | true
bitbucket | 1.1.11 | true
bitbucket-approval-filter | 1.0.3 | true
bitbucket-build-status-notifier | 1.4.2 | true
bitbucket-oauth | 0.10 | true
bitbucket-push-and-pull-request | 2.3.3 | true
bitbucket-scm-filter-jira-validator | 0.1.0 | true
blueocean | 1.23.1 | true
blueocean-autofavorite | 1.2.4 | true
blueocean-bitbucket-pipeline | 1.23.1 | true
blueocean-commons | 1.23.1 | true
blueocean-config | 1.23.1 | true
blueocean-core-js | 1.23.1 | true
blueocean-dashboard | 1.23.1 | true
blueocean-display-url | 2.3.1 | true
blueocean-events | 1.23.1 | true
blueocean-git-pipeline | 1.23.1 | true
blueocean-github-pipeline | 1.23.1 | true
blueocean-i18n | 1.23.1 | true
blueocean-jira | 1.23.1 | true
blueocean-jwt | 1.23.1 | true
blueocean-personalization | 1.23.1 | true
blueocean-pipeline-api-impl | 1.23.1 | true
blueocean-pipeline-editor | 1.23.1 | true
blueocean-pipeline-scm-api | 1.23.1 | true
blueocean-rest | 1.23.1 | true
blueocean-rest-impl | 1.23.1 | true
blueocean-web | 1.23.1 | true
bouncycastle-api | 2.18 | true
branch-api | 2.5.6 | true
build-timeout | 1.19.1 | true
build-token-root | 1.6 | true
build-token-trigger | 1.0.0 | true
cloud-stats | 0.25 | true
cloudbees-bitbucket-branch-source | 2.8.0 | true
cloudbees-folder | 6.12 | true
codebuilder-cloud | 1.0.1 | true
codecommit-url-helper | 0.0.3 | true
codedeploy | 1.23 | true
command-launcher | 1.4 | true
config-file-provider | 3.6.3 | true
configuration-as-code | 1.39 | true
console-badge | 1.1 | true
console-column-plugin | 1.5 | true
convert-to-pipeline | 1.0 | true
credentials | 2.3.7 | true
credentials-binding | 1.22 | true
dashboard-view | 2.12 | true
dependencyanalyzer | 0.7 | true
display-url-api | 2.3.2 | true
docker-build-step | 2.4 | true
docker-commons | 1.16 | true
docker-java-api | 3.1.5.2 | true
docker-plugin | 1.2.0 | true
docker-slaves | 1.0.7 | true
docker-workflow | 1.23 | true
durable-task | 1.34 | true
ec2 | 1.50.1 | true
email-ext | 2.69 | true
enhanced-old-build-discarder | 1.4 | true
external-monitor-job | 1.7 | true
favorite | 2.3.2 | true
generic-webhook-trigger | 1.67 | true
git | 4.2.2 | true
git-client | 3.2.1 | true
git-server | 1.9 | true
github | 1.29.5 | true
github-api | 1.111 | true
github-branch-source | 2.7.1 | true
github-oauth | 0.33 | true
github-scm-filter-jira-validator | 0.1.0 | true
google-login | 1.6 | true
google-metadata-plugin | 0.3.1 | true
google-oauth-plugin | 1.0.0 | true
google-play-android-publisher | 3.0 | true
google-source-plugin | 0.4 | true
gradle | 1.36 | true
gravatar | 2.1 | true
h2-api | 1.4.199 | true
handlebars | 1.1.1 | true
handy-uri-templates-2-api | 2.1.8-1.0 | true
htmlpublisher | 1.22 | true
itms-for-jira | 1.4 | true
jackson2-api | 2.11.0 | true
javadoc | 1.5 | true
jaxb | 2.3.0.1 | true
jdk-tool | 1.4 | true
jenkins-design-language | 1.23.1 | true
jenkins-jira-issue-updater | 1.18 | true
jira | 3.0.15 | true
jira-ext | 0.9 | true
jira-steps | 1.5.4 | true
jira-trigger | 1.0.0 | true
JiraTestResultReporter | 2.0.7 | true
job-dsl | 1.77 | true
jquery | 1.12.4-1 | true
jquery-detached | 1.2.1 | true
jquery-ui | 1.0.2 | true
jsch | 0.1.55.2 | true
junit | 1.29 | true
lambda-test-runner | 0.1.0 | true
ldap | 1.24 | true
libvirt-slave | 1.8.5 | true
lockable-resources | 2.8 | true
log-file-filter | 1.11 | true
mailer | 1.32 | true
managed-scripts | 1.4 | true
mapdb-api | 1.0.9.0 | true
matrix-auth | 2.6 | true
matrix-project | 1.14 | true
maven-info | 0.2.0 | true
maven-plugin | 3.6 | true
mercurial | 2.10 | true
momentjs | 1.1.1 | true
msbuild | 1.29 | true
mstest | 1.0.0 | true
mstestrunner | 1.3.0 | true
multiple-scms | 0.6 | true
node-iterator-api | 1.5.0 | true
oauth-credentials | 0.4 | true
oic-auth | 1.7 | true
pam-auth | 1.6 | true
pipeline-aws | 1.41 | true
pipeline-build-step | 2.12 | true
pipeline-config-history | 1.6 | true
pipeline-github | 2.5 | true
pipeline-github-lib | 1.0 | true
pipeline-graph-analysis | 1.10 | true
pipeline-input-step | 2.11 | true
pipeline-maven | 3.8.2 | true
pipeline-milestone-step | 1.3.1 | true
pipeline-model-api | 1.6.0 | true
pipeline-model-declarative-agent | 1.1.1 | true
pipeline-model-definition | 1.6.0 | true
pipeline-model-extensions | 1.6.0 | true
pipeline-multibranch-defaults | 2.1 | true
pipeline-rest-api | 2.13 | true
pipeline-stage-step | 2.3 | true
pipeline-stage-tags-metadata | 1.6.0 | true
pipeline-stage-view | 2.13 | true
pipeline-timeline | 1.0.3 | true
pipeline-utility-steps | 2.5.0 | true
plain-credentials | 1.7 | true
powershell | 1.4 | true
publish-over | 0.22 | true
publish-over-ssh | 1.20.1 | true
pubsub-light | 1.13 | true
qmetry-for-jira-test-management | 1.15 | true
release-helper | 1.3.3 | true
remote-file | 1.9 | true
resource-disposer | 0.14 | true
role-strategy | 2.16 | true
saml | 1.1.5 | true
scalable-amazon-ecs | 1.0 | true
scm-api | 2.6.3 | true
script-security | 1.71 | true
simple-theme-plugin | 0.6 | true
slack | 2.40 | true
snakeyaml-api | 1.26.4 | true
spotinst | 2.0.20 | true
sse-gateway | 1.23 | true
ssh | 2.6.1 | true
ssh-credentials | 1.18.1 | true
ssh-slaves | 1.31.2 | true
ssh-steps | 2.0.0 | true
ssh2easy | 1.4 | true
stashNotifier | 1.20 | true
structs | 1.20 | true
subversion | 2.13.1 | true
timestamper | 1.11.3 | true
tm4j-automation | 1.5.1 | true
token-macro | 2.12 | true
trilead-api | 1.0.6 | true
variant | 1.3 | true
vs-code-metrics | 1.7 | true
vstestrunner | 1.0.8 | true
webhook-step | 1.4 | true
windows-slaves | 1.6 | true
workflow-aggregator | 2.6 | true
workflow-api | 2.40 | true
workflow-basic-steps | 2.20 | true
workflow-cps | 2.80 | true
workflow-cps-global-lib | 2.16 | true
workflow-durable-task-step | 2.35 | true
workflow-job | 2.39 | true
workflow-multibranch | 2.21 | true
workflow-scm-step | 2.11 | true
workflow-step-api | 2.22 | true
workflow-support | 3.4 | true
ws-cleanup | 0.38 | true
xray-connector | 2.2.0 | true
zephyr-for-jira-test-management | 1.5 | true

**Comment by slide** [comment]
Your log and image version don't match up. The log reports `Remoting version: 4.2` but you say you are specifying `jenkins/slave:3.27-1`? Are you building your own image based on this image? Can you provide your Dockerfile if so? How are you launching the container?

**Comment by GioMac** [comment]
@slide 
after removing image:
```
Start Docker container to host the build
Error: No such volume: c674cc1d5ced7018d5befde55309530a6d1f273a4da40073ffe89d85880d5374
Unable to find image 'jenkins/slave:3.27-1' locally
Trying to pull repository docker.io/jenkins/slave ... 
3.27-1: Pulling from docker.io/jenkins/slave
```
image list:
```
[root@jenkins ~]# docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
docker.io/jenkins/slave   3.27-1              783c200a4398        18 months ago       628 MB
```

**Comment by slide** [comment]
That is a pretty old version of the agent image, is there a specific reason you are using one that old? I would recommend updating to `jenkins/agent:4.3-4` which has several security related fixes and more testing.

**Comment by timja** [comment]
no response in over a year, closing
